vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        # skills:
        #     uri_prefix: /images/skills
        #     upload_destination: '%kernel.project_dir%/public/images/skills'
        #     inject_on_load: false
        #     delete_on_update: true
        #     delete_on_remove: true

